### ISSUE TITLE
unbound variable EPOCHREALTIME

### ISSUE THREAD

**Issue by bbortt** [krzko/opentelemetry-shell#49]
#### Describe the bug

hi there! great lib, I wanted to use it for monitoring some bash scripts behavior. however, running [the `README.md` traces sample](https://github.com/krzko/opentelemetry-shell#trace-example) ends up in an error in plain bash Docker runtime:

```shell
./spam.sh

 _____ _____ _____ _____ _____ _____ __    _____ _____ _____ _____ _____ __ __
|     |  _  |   __|   | |_   _|   __|  |  |   __|     |   __|_   _| __  |  |  |
|  |  |   __|   __| | | | | | |   __|  |__|   __| | | |   __| | | |    -|_   _|
|_____|__|  |_____|_|___| |_| |_____|_____|_____|_|_|_|_____| |_| |__|__| |_|
 _____ _____ _____ __    __
|   __|  |  |   __|  |  |  |
|__   |     |   __|  |__|  |__
|_____|__|__|_____|_____|_____|

2022-10-04 15:41:58 [INFO] [spam.sh#L43] [source()] Initialising OpenTelemetry Shell v0.0.8
/appl/otello/opentelemetry-shell/library/time.sh: line 34: EPOCHREALTIME: unbound variable
2022-10-04 15:41:58 [INFO] [spam.sh#L10] [sleep_for()] Sleeping for 1 sec...
/appl/otello/opentelemetry-shell/library/time.sh: line 34: EPOCHREALTIME: unbound variable
2022-10-04 15:41:59 [ERROR] [spam.sh#L41] [net_client_post()] The requested URL returned an error: https://[OMITTED]/v1/traces
```

it looks like `$EPOCHREALTIME` was [not expanded properly](https://github.com/krzko/opentelemetry-shell/blob/main/library/time.sh#L34).

#### To Reproduce

1. get some linux Docker image
2. clone the repository on `main` (btw you didn't tag `v0.0.8` yet)
3. copy paste the traces sample
4. run it

#### Expected behavior

since I do not have the `$EPOCHREALTIME` defined, it should use date instead.

#### Screenshots

see bash output above.

#### Environment

- a plain linux in Docker, having installed `curl`, `git`, `hostname` and `jq`

#### Additional context

-

**Comment by bbortt** [comment]
I can provide the fix this evening, btw...

```shell
$ git diff
diff --git a/library/time.sh b/library/time.sh
index 8219a8c..004f63d 100644
--- a/library/time.sh
+++ b/library/time.sh
@@ -31,7 +31,7 @@ get_epoch_now() {
       log_debug "Using gdate..."
     fi
     epoch="$(gdate +%s.%N)"
-  elif [ "${EPOCHREALTIME}" ]; then
+  elif [ -n "${EPOCHREALTIME-}" ]; then
     if [ -z "${OTEL_LOG_LEVEL-}" ]; then
       log_debug "Using ${EPOCHREALTIME}..."
     fi
```

**Comment by bbortt** [comment]
@krzko also, what is keeping you from tagging `v0.0.8` if I might ask? I'd feel a bit safer with a "stable" release/version 😅

**Comment by krzko** [comment]
Hi @bbortt thanks for contributing 🙌 

Good catch with the variable. It's been a lot of trialling on different systems, must have had the reverse condition listed. Thanks for adding the solution.

With the release, am looking at getting `brew` to deploy it all, once I can get that stable, then I'll `0.1.0` it 😄

**Comment by bbortt** [comment]
no problem, thanks for accepting the PR. and stable version with brew sounds good to me.

so it's all manually tested? I saw that you also started a `tests` folder. but it looks like Docker images used for testing, not actual tests. is that correct?

**Comment by krzko** [comment]
Yeah, that plan was to add some functional tests as an action, to ensure that the current implementation works with the ever changing OTEL landscape.

Was planning on running a bunch of telemetry tests into a local otelcol and then fail on erroneous runs. Still need to do, time permitting. 😄
