### ISSUE TITLE
define service.name on users request only

### ISSUE THREAD

**Issue by bbortt** [krzko/opentelemetry-shell#53]
#### Is your feature request related to a problem?

(I love this issue template)

**I'm always frustrated** when something overwrites my `service.name`. actually, the change introduced [in #51](https://github.com/krzko/opentelemetry-shell/pull/51/files#diff-196a2d802b8397571ec8d2f27c2c952cbb695517a5513980604afb44e0865e2dR22) (to append the `service.name` optionally) is probably not that useful. shortly after, I've noticed that "someone else" is now overwriting my globally defined `service.name` with the bash script name.

that is, in my opinion, also not compliant with [the documentation](https://github.com/krzko/opentelemetry-shell#environment-variables). because the global variable literally just gets thrown away.

#### Describe the solution you'd like

I don't know if this was a design goal. but, I'd suggest to add explicit properties instead: "if you're a bash script and this property is true, add your name" or "if you are a gitlab pipeline and that (another) property is true, add your name".

##### making every appendance optional

(like I did in #51)

this way, nobody overwrites my globally defined `service.name`. on the other hand, the order of the (internal) scripts will then matter, as just the very first one will add its service name. when the code reaches the other ones, it's already done.

opinions @krzko?

**Comment by krzko** [comment]
This makes sense, if the OTEL_SERVICE_NAME is set, then it should not be overwritten as its been explicitly defined prior to invocation.

I guess the detectors in this case will be overwriting the value, as it'll take in the repo no by default. Will look at performing a conditional there, if set, ignore and leave `service.name` as is.

**Comment by krzko** [comment]
Working on other optimisations at the moment, so will look to the add the above in as well. Thanks for highlighting it.

**Comment by krzko** [comment]
This should work for you now as have just merged https://github.com/krzko/opentelemetry-shell/pull/55.

Let me know if that works as expected for you. The functionality should will align to the specs now.

If no `OTEL_SERVICE_NAME` var is defined, `service.name=unknown_service`. The detectors will then use the repo name.

If `OTEL_SERVICE_NAME` is defined, then this will propagate through and will be primary source for `service.name`.

**Comment by bbortt** [comment]
that sounds good to me. I've also looked ad #55 and it seems to work. thanks!
